<a href="https://colab.research.google.com/github/Nilesh-Gupta6263/python-learning/blob/main/Copy_of_python_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 # from typing_extensions import get_overloads
# print ("if you have any doubt the following progarm , code identation and sytax plese go to w3 pythin school and read the concept ")
# print("hay bhagwan bcha lena")
# print ("radhe rahde")
# print("import.sys")
# name = "nilesh gupta"  # varriable
# age = 18
# city = 'bhopal'
# print (name,city,age)
# name = input('what in your name and what are you doing in bhopal')
# #print("my name is nilesh gupta ") #comment
# print('my name is nilesh gupta')
# #i have done my 10th from assm school gurh rewa
# #i have done my 12th from govt school from gurh rewa
# #now i am persuing my b tech from vist collage bhopal # it defene the comment for testing the code
# print("i have done my 10th from assm school gurh rewa and i have done my 12th from govt school from gurh rewa and now i am persuing my b tech from vist collage bhopal ")
# '''as i am
# i am good
# and i think
# i dont need to proove it'''
# print('As i am i am good and ithink i dont need to proove it')
# x = 478 #it is (int data type) no need of any indetation
# y = 'anuprash gupta' #quote ('')and("") is important for define the (string data type) otherwise program will give error
# z = 4789.96#it is a (flowt data type) no need of any indetation
# print(x,y,z)
# print (x)
# print(y)
# print(z)
# p = 'satyamev jayte'
# p = 869  #p is a same varriable
# print(p)
# a = int(100) #it will be 100
# b = str(100)#it will be '100'
# c = float(100)#it will be 100.0
# print(a,b,c)
# print(a)
# print(b)
# print(c)
# a='nothing is impossible'
# A='everything is possible'
# print(a)
# print(A)

In [ ]:
print("radhe radhe")
print("hellow world")

#comment
#there two type of comment are prensent in prthon one is single line (#) and second is ('''   ''') and ("""  """)which is called multiline comment

#hey nilesh, please dont remove this line
#Author:Nilesh gupta                         # this is a single comment
#course : 100 days of code
print(" hey dude remember that line\n  \"accept your destiny and go to ahead with your life\"")   # \n = escape sequence character use for change the paragraph
print("\n")      # \n = escape sequence character use for change the paragraph
                  #\" \"  = escape sequence character use for represent the double and single quote
print("radhe ardhe")


 #comment
''' there two type of comment are prensent in prthon one is single line (#) and second is ('''   ''') and ("""  """)which is called multiline comment

hey nilesh, please dont remove this line
Author:Nilesh gupta ''' #this is multiline comment

print('all is well \n enough your drama')
print("dont hurt anyone")
print("dont even think so")

# \n = escape sequence character use for change the paragraph
                 #\" \"  = escape sequence character use for represent the double and single quote
print("dont forget it \n \"if you practice more ou will defenately learn more\"")
print("can i ask you something\n why not \n do you want to \"learn english\" \n yes offcourse")
print('\"dont hurt anyone\"')
print(" \'dont hurt anyone\' ")
print("hey\' \"i am nilesh gupta\"") #\'  = escape sequence character use for represent the  single quote
#object(S) = we can write here multiple type of data value
print("we can write here multiple type of value",37,83,)
print("we can write here multiple type of value",37+83,6*6,10-7)
#seperator = seperate the multiple value
print("me can write here multiple type of value",37,83, sep="~")
print("we can write here multiple type of value",37+83,6*6,10-7,sep="~")
#end = end value add at end of the line or statement
print("we can write here multiple type of value",37+83,6*6,10-7,sep="~",end="i am add at the end")
print("\n dont go anywhere because i am here")

print("we can write here multiple type of value",37+83,6*6,10-7,sep="~",end="i am add at the end\n")
print("dont go anywhere because i am here")

radhe radhe
hellow world
 hey dude remember that line
  "accept your destiny and go to ahead with your life"


radhe ardhe
all is well
 enough your drama
dont hurt anyone
dont even think so
dont forget it
 "if you practice more ou will defenately learn more"
can i ask you something
 why not
 do you want to "learn english"
 yes offcourse
"dont hurt anyone"
 'dont hurt anyone'
hey' "i am nilesh gupta"
we can write here multiple type of value 37 83
we can write here multiple type of value 120 36 3
me can write here multiple type of value~37~83
we can write here multiple type of value~120~36~3
we can write here multiple type of value~120~36~3i am add at the end
 dont go anywhere because i am here
we can write here multiple type of value~120~36~3i am add at the end
dont go anywhere because i am here

In [ ]:
print("radhe radhe")
#Varriable and data types

A=568
b=748
k= None
p=True
C="radhe radhe"
print(A)
print(b)
print(C)
print(k)
print(p)
a=complex(3,5)
print(a)

name = "Nilesh gupta"
age = 18.5
course = "Btech"
print("this is name of :",type (name))
print("this is age of nilesh gupta:",type (age))
print("this is course of nilesh gupta:",type (course))

List1=[8,2.3,[-4,56],["apple","i will slap you"],"shree seetaram"]
print(List1)

tuple1=(8,2.3,[-4,56],["apple","i will slap you"],"shree seetaram")
print(tuple1)

dict1 = {"name":"nilesh gupta", "age":18, "course":"btech"}
print(dict1)

radhe radhe
568
748
radhe radhe
None
True
(3+5j)
this is name of : <class 'str'>
this is age of nilesh gupta: <class 'float'>
this is course of nilesh gupta: <class 'str'>
[8, 2.3, [-4, 56], ['apple', 'i will slap you'], 'shree seetaram']
(8, 2.3, [-4, 56], ['apple', 'i will slap you'], 'shree seetaram')
{'name': 'nilesh gupta', 'age': 18, 'course': 'btech'}

In [ ]:
# print("radhe radhe")
# #first project like a calculator
# #creatation of calculator which capable of substraction ,addition ,multiplication,division,modulus and floor division

# m=8
# n=3
# ans1=m+n
# print("additinon of",n,"and",m,"is", ans1)
# ans2=m-n
# print("substraction of",n,"and",m,"is",ans2)
# ans3=m*n
# print("multiplication of",n,"and",m,"is",ans3)
# ans4=m/n
# print("divition of",n,"and",m,"is",ans4)
# ans5=m%n
# print("modulus of",n,"and",m,"is",ans5)
# ans6=m//n
# print("floor division of",n,"and",m,"is",ans6)
# print(ans1)
# print(ans2)
# print(ans3)
# print(ans4)
# print(ans5)
# print(ans6)
# print(type(ans1))
# print(type(ans2))
# print(type(ans3))
# print(type(ans4))
# print(type(ans5))
# print(type(ans6))

# a=30
# b=5
# print("the value of",a,"+",5,"is",a+b)
# print("the value of",a,"-",5,"is",a-b)
# print("the value of",a,"*",5,"is",a*b)
# print("the value of",a,"/",5,"is",a/b)

In [ ]:
# print("radhe radhe")
# #type casting or data type conversion
# '''there are two main type of type casting
# 1.explicit data type conversion
# 2.implicit data type conversion '''

# a=15.4758
# b=74647
# c="nilesh gupta"
# print(int(a))
# print(float(b))
# print(str(c))
# print(int(a)+int(b))
# print(float(a)-float(b))

# p=2
# t=34
# print(str(p)+str(t))
# print(float(p)+float(t))
# print(p+t)

# #explicit data type casting

# string="3764"
# number=487
# string_number=int(string)
# sum=number+string_number
# print("the sum of both the number is:",sum)

# #Implicit data type casting

# a=8
# print(type(a))
# b=8.7
# print(type(b))
# c=a+b
# print(c)
# print(type(c))

In [ ]:
print("radhe radhe")
#user Input in python
a= (input("enter your name:"))
print("my name is \"nilesh gupta\".")
c=(input("what is your weakness:"))
print("ok nilesh gupta tell me about your weakness?\n",c)

b=(input("what is the key of success:"))
print("always remember one thing:\n",b)

x=(input("enter any one digit:"))
y=(input("enter any one digit"))
print(x+y)

p=(input("what do you want to become:"))
q=(input("why do you want to become a devloper: "))
print(p+q)

#python interpreter consider every data as a string hence we need to explain that

j=(input("enter any one digit"))
k=(input("enter any one digit"))
print(int(j)+float(k))
print(float(j)+float(j))

radhe radhe

In [ ]:
print("radhe radhe")
#String

name="Nilesh"
frind="manoj"
otherfriend='satyam'
print("hello,what do you want to do in your life "+name)
name='Nitin'
print('hello, my name is '+name,'i want to beacome a \"skilled full devloper\"')

phone="""hello is this nilesh gupta speaking
       yes this is nilesh gupta speaking
       ok nilesh so tell me is this right time to words with you
       oo ya offcourse tell me nilesh what happened"""
print(phone+"this is a right way of talking to anyone from phone/nthank you so much"  )

phone='''hello is this nilesh gupta speaking\'
       yes this is nilesh gupta speaking\'
       ok nilesh so tell me is this right time to words with you\'
       oo ya offcourse tell me brother what happened.'''
print(phone+"this is a right way of talking to anyone from phone/nthank you so much"  )

#indexing(array) in python

a_b="vivekanand\n"
b_a="shivaji\n"
a="shailigupta,gayatrishahu\n"
print(a_b[0])
print(a_b[1])
print(a_b[2])
print(a_b[3])
print(a_b[4])
print(a_b[5])
print(a_b[6])
print(a_b[7],"\n")

print(b_a[0])
print(b_a[1])
print(b_a[2])
print(b_a[3])
print(b_a[4])
print(b_a[5])
print(b_a[6],"\n")
# print(b_a[7])

print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print(a[5])
print(a[6])
print(a[7])
print(a[8])
print(a[9])
print(a[10])
print(a[11])
print(a[12])
print(a[13])
print(a[14])
print(a[15])
print(a[16])
print(a[17])
print(a[18])
print(a[19])
print(a[20])
print(a[21])
print(a[22])
print(a[23], "\n")



a_b="vivekanand\n"
b_a="shivaji\n"

for character in a_b:
  print(character)
for words in b_a:
  print(words)

a="shailigupta,gayatrishahu"
for character in a:
  print(character)

  #string length of slice

name="Nileshgupta"
print(len(name))

len1=len("nilesh gupta")
print(len1)

a="guptaji"
b="bikashgupta"
c=(a+b)
print(len(c))

fruit=("mango")
len1=len(fruit)
print("mango is a" , len1,"letter word.")
print(fruit[0:4])  # python interpreter including 0 but not 4
print(fruit[:4])   #  python interpreter including automatically 0
print(fruit[1:4])
print(fruit[:5])
print(fruit[1:])
print(fruit[:])

#negative
name="stomach"
print(name[len(name)-5:len(name)-4])
print(name[-5:-4])        #both are same

print(name[0:-4])
print(name[0:len(name)-4])  #both are same
print(name[:-4])
print(name[-1:-4])
print(name[:-5])
print(name[-1:])

#quiz

nm="harry"
print(nm[-4:-2])
print(nm[len(nm)-4:len(nm)-2])  # both are same


#there are many types of methodes to represent the string

# 1. Upper()
a="nilesh"
print(a.upper())   #strings are immutable

b="dont make a cock and bull story because i know everything"
print(b.upper())

c="I Dont have any work"
print(c.upper())

# 2.lower()
d="EXAGGERATE"
e="Exaggerate"
f="boast"
print(d.lower())
print(e.lower())
print(f.lower())

# 3.rstrip()
x="i am a son of mr.satyanarayan gupta?!!!"
print(x.rstrip("!"))
y="i am thirsty ///"
print(y.rstrip("/"))
z="am i angry with you???"
print(z.rstrip("?"))

# 4.replace()
p="nilesh"
print(p.replace("nilesh","nitin gupta"))
q="do you want to come on the stage?"
print(q.replace("do you want to come on the stage?","no i dont want"))
r="do you love me"
print(r.replace("do you love me","no nilesh i love nitin"))

# 5.split()
s="nilesh bikash ritesh suraj sidhanshu shudhanshu dipanshu"
print(s.split())
t='appreciate insult prctice dailypractice'
print(t.split())
u='what why how whose where whome'
print(u.split())

# 6.capitalize()
my="what do you want to do"
print(my.capitalize())
ny="who says speaking english is tough"
print(ny.capitalize())
py="speaking english is as easy as writing english"
print(py.capitalize())

# 7.center()
hy="welcome to the hart of my love"
print(hy.center(50))
print(hy.center(50,"*"))
print(hy.center(50,"$"))
by="what ever you said is 100% right"
print(by.center(50))
print(by.center(50,"*"))
print(by.center(50,"$"))
jy="english is being spoken across the world"
print(jy.center(80))

#8.count()
ty="thanku thanku thanku so much"
print(ty.count("thanku"))
sy='you dont make mistake because you always think first'
print(sy.count("think"))
wy='english must must must very must be spoken'
print(wy.count("must"))

# 9.endswith()
dy="when you speak by think so you dont make mistake.."
print(dy.endswith(".."))
ay="would you like to go there?"
qy='yes i would like to go there!!!'
print(qy.endswith("!"))
print(ay.endswith("?"))
print(qy.endswith("?"))
print(ay.endswith("!"))

# 10.find()
pk='as i am i am good and i think i dont need to proove it thanks'
print(pk.find("proove"))
sk='''if you practice more
           you will defenately learn more
           so please i request you dont waste your expensive time'''
print(sk.find("defenately"))
dk="""my strength is my parentes,elder brother,teachers and all friends
                 because they always supporting me apart from i have good communication skills,
                 good problem solving skills with strong will power"""
print(dk.find("too")) # if the word is not present in string it will give -1
print(dk.find("will power"))

#11.index()
hk='''and i dont about my weakness what my weakness is but i am very emotional
        i think its my weakness'''
print(hk.index("emotional"))
fk='''my name is nilesh gupta basically i am from rewa and i have done my 10th from assm public
      school (mp board) and 12th from govt higher secondary school (mp board) rewa'''
print(fk.index("12th"))
#print(fk.index("high school")) il will give error

# 12.isalnum()
kk="letmesleepiamgettinglate142"
print(kk.isalnum())
gg='stop your gimmick ' #no need of any space any panctuation
print(gg.isalnum())
jj='i will help you but i have a condition!'
print(jj.isalnum())

# 13.isalpha()
bk="letmesleepiamgettinglate142"
print(kk.isalpha())
uk="nilesh143"             #it is same as the isalnum but numbers are not allowed
print(uk.isalpha())
vk="nileshgupta"
print(vk.isalpha())

# 14.islower()
ll="i dont know whatever you know"
print(ll.islower())
mm="i wish you were mine"
print(mm.islower())
nn="Can I Ask You Somthing"
print(nn.islower())

#15.isprintable()
ok="study as much you can\n otherwise you will surely fail got is"
print(ok.isprintable())
os="study as much you can otherwise you will surely fail got is"
print(ok.isprintable())
op='i dont need your help i can help my self so please brother dont argue with me'
print(op.isprintable())

# 16.isspace()
bb="            "
print(bb.isspace())
cc=""
print(cc.isspace())

# 17.title()

aa="World Health Organization"
print(aa.istitle())
kk="world health organization"
print(kk.istitle())
ee="i love you"
hh="I Love You"
print(ee.istitle())
print(hh.istitle())

# 18.isupper()
bmw="FIGHT YOUR SELF OTHERWISE YOU WILL LOSS YOUR EVERYTHING"
H=bmw
print(H.isupper())
tata='whatever comes in your mind think in english and speak english'
print(tata.isupper())
mi="BEING A GOOD HUMAN IT IS YOUR RESPONSSIBILITY TO SHOW OWN HUMANITY"
IPHONE=mi
print(IPHONE.isupper())

# 19.startswith()
rcb='I know why you are learning english but i dont mind keep learning'
csk=rcb
print(csk.startswith("I"))
kkr="i am ready to do everything"
print(kkr.startswith("am"))
srh='please i humble request go toward success'
print(srh.startswith("please"))

# 20.swapcase()
rr='I KNOW WHAT DO YOU WANT TO DO'
print(rr.swapcase())
gt="can you walk with me untill the end of life"
print(gt.swapcase())
lsg="you are born to achieve something NEW "
print(lsg.swapcase())

# 21.title()
rr='I KNOW WHAT DO YOU WANT TO DO'
print(rr.title())
gt="can you walk with me untill the end of life"
print(gt.title())
lsg="you are born to achieve something NEW "
print(lsg.title())

In [ ]:
print("radhe radhe")
# if and else statement
'''conditional operator:
                        > , < , >= , <= ,== ,   != (operator of not equal)
'''

a=int(input("enter your age:"))
print("your age is :",a)
print(a<18)
print(a>18)
print(a==18)
print(a!=18)
print(a<=18)
print(a>=18)
if(a>18):
  print("you are eligible to vote")
  print("thank you")
else:
  print("you are not eligible to vote")
  print("thank you")

a=20
print("your age is :",a)
print(a<18)
print(a>18)
print(a==18)
print(a!=18)
print(a<=18)
print(a>=18)
if(a>18):
  print("you are eligible to vote")
  print("thank you")
else:
  print("you are not eligible to vote")
  print("thank you")

print("nilesh") #it is out of the range of if else statement

appleprice=int(input("enter the price of apple:"))
bugget=300
if(appleprice!=bugget and appleprice<bugget):
  print("buy the 1 kg apple" )
  print("thanku")
else:
  print("do not buy the apple")

age1="20"
age2=int(age1)
if(age2>18):
  print("yes")
  print("you can drive")
  print("thanks")
else:
  print("no chance")
  print("you can not drive")
  print("thanks")

#  elif statement


age1="17"
age2=int(age1)
if(age2>18):
  print("yes")
  print("you can drive")
  print("thanks")
elif(age2==17):
  print(" please wait")
  print("you can drive after one year")
  print("thank you")
else:
  print("no chance")
  print("you can not drive")
  print("thanks")

#we can add the more than one elif statement

num=int(input("enter the value of num:"))
if(num<0):
  print("number is negative")
elif(num==99):
  print("special number is 99")
elif(num==100):
  print(" 100 is lucky number ")
else:
  print("number is positive")

# nested if statement
# we can add another if else statement inside the if else statement and elif statement

num = 18
if(num<0):
  print("number is negative")
elif(num>0):
    if(num<=0):
       print("number is between 1-10")
    elif(num>10 and num<=20):
       print("number between 11-20")
    else:
      print("number is greather than 20")
else:
  ("number is zero")

In [ ]:
print("radhe radhe")
#exercise
#time module
import time
timestamp =time.strftime("%H:%m:%S")
print(timestamp)
timestamp= int(time.strftime("%H"))
print(timestamp)
timestamp=time.strftime("%m")
print(timestamp)
timestamp=time.strftime("%s")
print("timestamp")


import time
t = time.strftime('%h:%m:%s:')
hour = int(time.strftime('%H'))
# hour = int(input("Enter hour"))
print(hour)

if(hour>=0 and hour<12):
  print("good morning sir")
elif(hour>=12 and hour<17):
  print("good afternoon sir")
elif(hour>=17 and hour<0):
  print("good night sir")

radhe radhe
20:06:12
20
06
timestamp
20

In [ ]:
print("radhe radhe")
#match statement
x=int(input("enter the value of x:"))
match x:
  case 0:
    print("x is zero")
  case 4:
    print("x is four")
  case 5:
    print("x is five")
  case 6:
    print("x is six")

y=int(input("enter the value of x:"))
match y:
  case 0:
    print("y is zero")
  case 4:
    print("y is four")
  case _ if y!=15:
    print("y is not equal to 15")
  case _ if y>15:
    print("y is greater than 15")
  case _ :
    print(y)

name=(input("enter the relation :"))
match name:
      case "brother":
        print("nilesh gupta is small brother of\'\"bikash gupta\"")
      case "son":
        print("nilesh gupta is  a son of\' \"mr. satyanarayan gupta\"")
      case "grandson":
        print("nilesh gupta is grandson of\'\"mr. Badri gupta\"")

In [ ]:
# print("radhe radhe")
# # information about for loops

# name="nitin"
# for name in name:
#   print(name)

# retional="\n how good"
# for i in retional:
#   print(i ,end=",")
#   if (i=="d"):
#     print("tulsi")

# students=["ram","shyam","gopal","madhav"]
# for i in students:
#   print(i)
#   if (i=="madhav"):
#     print("ram,shyam,gopal are good name infact very good name but madhav lovely name")

# #range() function:
# for k in range(5):
#   print(k)
#   print(k+1)
#   print(k+2)
#   print(k+3)

# for numbers in range(10,100):
#   print(numbers)

# for numbers in range(10,100,5):
#   print(numbers)
#   print(numbers+1)

In [ ]:
print("radhe radhe")

#while loop
                #increamental while loop
a=0
while(a<3):
  print(a)
  a=a+1
print("done with the while loop") #out of the while loop range

b=0
while(b<=3):
  print(b)
  b=b+1
  print("done with the while loop") #inside the while loop the while loop range

easygoing=int(input("enter the value of easygoing:"))
while(easygoing<=7):
  print(easygoing)
  easygoing=easygoing+1
  print("done with the while loop") #inside the while loop the while loop range

easygoing=int(input("enter the value of easygoing:"))
while(easygoing<=7):
  easygoing=int(input("enter the value of easygoing:"))
  print(easygoing)
  easygoing=easygoing+1
  print("enter the next value")

# decreamental while loop

bossy=6
while(bossy>=0):
  print(bossy)
  bossy=bossy-1

ram=10
while(ram>=5):
  print(ram)
  ram=ram-1

om=15
while(om<=20):
  print(om)
  om=om+1

crazy=100
while(crazy>=95):
  print(crazy)
  crazy=crazy-1

plucky=89
while(plucky>=70):
    print(plucky)
    plucky=plucky-2

neat=101
while(neat<=120):
  print(neat)
  neat=neat+19

scared=int(input("enter"))
while(scared<=89):
  scared=int(input("enter"))
  print(scared)
  print("next number please")



#  while loop + else

count=-5
while(count==1):
  print(count)
  count=count+1
else:
  print("hello i am inside the else")

count=-5
while(count<=1):
  print(count)
  count=count+1
else:
  print("hello i am inside the else")

In [ ]:
print("radhe radhe")

#Break and contineu  statement
for i in range (12):
 print("5*",i+1,"=",5*(i+1) )
 if(i==10):
  break
print("is loop ko chood ke nikal jao")

for i in range (12):
 print("5*",i,"=",5*i )
 if(i==10):
  print("is loop ko chood ke nikal jao")
  break                # stop after given condition


for i in range (12):
 if(i==10):
   print("skip the iteration")
   continue
 print("5*",i,"=",5*(i))     #skip only given condition
print("kash maine achhe krma kiye hote")

for stubborn in range(10):
  print("10 *",int(((stubborn+1)*10)/10),"=",(stubborn+1)*10)
  if(stubborn==80):
    print("stop here dont go ahead")
    break

for stubborn in range(10):
  if(stubborn==7):
    print("stop here dont go ahead")
    continue
  print("10 *",int(((stubborn+1)*10)/10),"=",(stubborn+1)*10)

for anxity in range (15):
  print("15-",15-(anxity),"=",anxity)
  if(anxity==11):
    print("sudhar ja")
    break

for anxity in range (15):
  if(anxity==11):
    print("sudhar ja")
    continue
  print("15-",15-(anxity+1),"=",anxity+1)
i=0
while True :
  print(i)
  i=i+1
  if (i%100==0):
    break

In [ ]:
# print("radhe radhe")
# """PYHTON FUNCTION

# def is a user define function"""
# a=9
# b=8
# gmean=(a*b)/(a+b)
# print(gmean)

# c=8
# d=7
# gmean1=(c*d)/(c+d)
# print(gmean1)

# #now we use python function
# def calculate(a,b):
#   mean=(a*b)/(a+b)
#   print(mean)
# def isgreater(a,b):
#   if(a<b):
#     print("first number is greater")
#   else:
#     print("second number is greater")
# def islesser(a,b):
#   pass         # mai baad me poora krunga abhi aage bd jao

# a=15
# b=23
# # if(a>b):
# #   print("first number is greater")
# # else:
# #   print("second number is greater")
# calculate(a,b)
# isgreater(a,b)

# c=10
# d=20
# # if(c<d):
# #   print("first number is greater")
# # else:
# #   print("second number is greater")
# calculate(c,d)
# isgreater(a,b)


# print("om")

# #FUNCTION ORGUMENT

# def average (a,b):
#   print("the average is",(a+b)/2)
# average(4,6)

# def average (a=9,b=1):
#   print("the average is",int((a+b)/2))
# average()

# def average (a=9,b=1):
#   print("the average is",((a+b)/2))
# average(1,5)


# def average (a=9,b=1):
#   print("the average is",((a+b)/2))
# average(5)  #consider a=5 and b=1


# def average (a=9,b=1):
#   print("the average is",((a+b)/2))
# average(b=5) #consider b=5 and b=9


# def average (a=9,b=1):
#   print("the average is",((a+b)/2))
# average(b=5,a=6) #we can change the order of a and b


# def average (a=9,b=1):
#   print("the average is",((a+b)/2))
# average(b=5)
# average(a=8)


# def average (a,b,c=9):
#   print("the average is",((a+b-c)/2))
# average(b=5,a=7) #consider b=5 and a=7

# def name(fname,mname="mridul",lname="sen"):
#   print("hello",fname,mname,lname)
# name("satyam","anubhav","shivendra")

# def average(*numbers):
#   print(type(numbers))
#   sum=0
#   for i in numbers:
#     sum=sum+i
#   print("average is:",sum/len(numbers))
# average(8,9,5,6)


# #RETURN STATEMENT
# def average(*numbers):
#   # print(type(numbers))
#   sum=0
#   for i in numbers:
#     sum=sum+i
#   return sum/len(numbers)
# c=average(8,9,5,6)
# print(c)

# def average(*numbers):
#   # print(type(numbers))
#   sum=0
#   for i in numbers:
#     sum=sum+i
#   return 89
# c=average(8,9,5,6)
# print(c)

# def average(*numbers):
#   # print(type(numbers))
#   sum=0
#   for i in numbers:
#     sum=sum+i
#   return 87  #only first return allow not other
#   return sum/len(numbers)
# c=average(8,9,5,6)
# print(c)

# def name(**name):
#   print(type(name))
#   print("hello",name["fname"],name["mname"],name["lname"])
# name(mname="mridul",lname="sen",fname="satyam")

In [ ]:

print("radhe radhe")
#PYTHON LIST (date type)

#it make for storing the multiple thing at single varriable

l=[3,5,6]
print(l)
print(type(l))

marks=[3,5,6,"nilesh",True,"shaili","gayatri","khushi","rediculous","humongous","monk"]  #python allow multiple type of data at list
print(marks)
print(type(marks))
print(marks[0])
print(marks[1])
print(marks[2])
print(marks[3])
print(marks[4])
#print(marks[5])
''' gives error because python interpreter
                     starts the counting from 0 not from 1'''
print(marks[-3]) #negative index
print(marks[len(marks)-3]) #positive index
print(marks[5-3]) #positive index
print(marks[2]) #positive index

if 7 in marks:
  print("yes thats in the list")
else:
  print("no")


if "6" in marks:
  print("yes thats in the list")
else :
  print("no")

#same things applies for strings as well
if "nil" in "nilesh":
  print("yes")
if "nul" in "nilesh":
  print("yes")

print(marks[:])
print(marks[0:len(marks)])
print(marks[1:])
print(marks[:2])
print(marks[1:-1])
print(marks[1:len(marks)-1])
print(marks)
print(marks[1:7])
print(marks[1:7:2])
print(marks[1:9:3])

#LIST COMPREHENSION

list=[i for i in range(9)]
print(list)

list1=[i*i for i in range(6)]
print(list1)

list3=[i*i for i in range(9) if i%2==0]
print(list3)

#method of list in python

r=[1,2,3,4,5]
print(r)
#append
r.append(9)  # usefull for adding new value at the end in tha list data type
print(r)
#sort       it help to arrange the value in a sequential order (increasing order)
p=[5,7,2,94,6,5]
print(p)
p.sort()
print(p)
r.sort()
print(r)

#sort(reverse = True)
p.sort(reverse = True)    #it help to arrange the value in a sequential order (decending order)
print(p)
r.sort(reverse = True)
print(r)

#reverse()    opposite that means right to left
p=[5,7,2,94,6,5]
p.reverse()
print(p)
r.reverse()
print(r)

#index()  #tell the number position in the index form
placid=[8,6,9,8,6,9,6,]
print(placid.index(8))
print(placid.index(9))
lively=[98,56,34,22,333,]
print(lively.index(333))
unpleasent=[15,6,622,26,416,]
print(unpleasent.index(26))

#count()
stubburn=[7,6,5,6,7,6,5,5,5,6,7,6,5,4]
print(stubburn.count(5))
print(stubburn.count(6))
print(stubburn.count(7))

#Copy() method
m=stubburn.copy()    #ye function sirf m me changes krega
m[0]=0
print(stubburn)
print(m)

rude=[6,2,6,3,3,7,5,6,9,7,]
print(rude)
nervous=rude.copy()
print(nervous)
nervous[5]=967
print(nervous)
nervous
nervous[8]=6263375697
nervous
rude

#insert() method
fareless=[00,98,886,7647,764,476757,8464,847,]
print(fareless)
fareless.insert(2,99999999) # index 2 pe is value ko insert kr do
fareless
fareless.insert(5,888888)  #index 5 pe is value ko insert kr do
print(fareless)

#extend () method
shy=[1,2,3,4,5,6,7,]
print(shy)
talktive=[100,101,102,103,104]
nilesh=shy+talktive
print(nilesh)           #temperary changes that means add two list shy and talktive
nilesh=talktive+shy
print(nilesh)

shy.extend(talktive)      #add talktive value in to shy (occure permanent changes in the list)
print(shy)
talktive.extend(shy)
print(talktive)           #add shy value to talktive

radhe radhe
[3, 5, 6]
<class 'list'>
[3, 5, 6, 'nilesh', True, 'shaili', 'gayatri', 'khushi', 'rediculous', 'humongous', 'monk']
<class 'list'>
3
5
6
nilesh
True
rediculous
rediculous
6
6
no
no
yes
[3, 5, 6, 'nilesh', True, 'shaili', 'gayatri', 'khushi', 'rediculous', 'humongous', 'monk']
[3, 5, 6, 'nilesh', True, 'shaili', 'gayatri', 'khushi', 'rediculous', 'humongous', 'monk']
[5, 6, 'nilesh', True, 'shaili', 'gayatri', 'khushi', 'rediculous', 'humongous', 'monk']
[3, 5]
[5, 6, 'nilesh', True, 'shaili', 'gayatri', 'khushi', 'rediculous', 'humongous']
[5, 6, 'nilesh', True, 'shaili', 'gayatri', 'khushi', 'rediculous', 'humongous']
[3, 5, 6, 'nilesh', True, 'shaili', 'gayatri', 'khushi', 'rediculous', 'humongous', 'monk']
[5, 6, 'nilesh', True, 'shaili', 'gayatri']
[5, 'nilesh', 'shaili']
[5, True, 'khushi']
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 4, 9, 16, 25]
[0, 4, 16, 36, 64]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 9]
[5, 7, 2, 94, 6, 5]
[2, 5, 5, 6, 7, 94]
[1, 2, 3, 4, 5, 9]
[94, 7, 6, 5, 5, 2]
[9, 5, 4, 3, 2, 1]
[5, 6, 94, 2, 7, 5]
[1, 2, 3, 4, 5, 9]
0
2
4
3
5
5
3
[7, 6, 5, 6, 7, 6, 5, 5, 5, 6, 7, 6, 5, 4]
[0, 6, 5, 6, 7, 6, 5, 5, 5, 6, 7, 6, 5, 4]
[6, 2, 6, 3, 3, 7, 5, 6, 9, 7]
[6, 2, 6, 3, 3, 7, 5, 6, 9, 7]
[6, 2, 6, 3, 3, 967, 5, 6, 9, 7]
[0, 98, 886, 7647, 764, 476757, 8464, 847]
[0, 98, 99999999, 886, 7647, 888888, 764, 476757, 8464, 847]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 100, 101, 102, 103, 104]
[100, 101, 102, 103, 104, 1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 100, 101, 102, 103, 104]
[100, 101, 102, 103, 104, 1, 2, 3, 4, 5, 6, 7, 100, 101, 102, 103, 104]

In [ ]:
# print("radhe radhe")
# #python tuples
# '''we can not perform change operation in tuple data type
# mostly similar to list data type'''

# k=(1)
# l=(1,)  #  , is neccessary in tuple data type other wise interpreter consider as int data type
# j=(1,2,3,4,5)
# print(type(k),k)
# print(type(l),l)
# print(type(j),j)

# tuple=(5,6,7,89,3,74,9,4,"ramji","shreehriwanshji")
# # tuple[2]=100      change is not possible
# print(type(tuple),tuple)
# print(len(tuple))

# tuple1=(5,6,7,89,3,74,9,4,"ramji","shreehriwanshji")
# print(tuple1[0])
# print(tuple1[1])
# print(tuple1[2])
# print(tuple1[-3])
# print(tuple[-5])
# # print(tuple[15]) # the element of that index is not exist in the tuple

# if "ramji" in tuple:
#   print("yes ramji present in the tuple")
# else:
#   print("no ramji is not present in the tuple")

# if "shreehriwanshji" in tuple:
#   print("yes present")
#   print("thanks",len("shreehriwanshji"))
# else:
#   print("no present")
#   print("thanks")

# tup2=tuple1[0:6]
# print(tup2)

# #mathods in tuple
countries=("India","Australiya","itli","jermni","nepal")
countries1=("Africa","japan","Americ")
asia=countries+countries1
print(asia)

#count () methode

tuple=(1,2,3,4,5,6,7,8,4,9,4,5,4,3,4,5,6)
res=tuple.count(4)
print('count of 4 in tuple is:',res)

#index()method
res=tuple.index(4)   # it give the index of first 4
print(res)
res=tuple.index(4,7,10) #  it shows the index of 4 at index7 to index10
print(res)
res=len(tuple)
print(res)

('India', 'Australiya', 'itli', 'jermni', 'nepal', 'Africa', 'japan', 'Americ')
count of 4 in tuple is: 5
3
8
17

In [ ]:
print("radhe radhe")

#EXercise 3
""" create a program capable of displaying questions to the user link.
use list data type to store the questions and there correct answer.
display the final amount to the person is taking home after playing the game.
"""

radhe radhe

In [ ]:
print("radhe radhe")
#f-string  (introduced in python 3.6)
senstive="hey my name is {} and i am from {}"
name="nilesh"
place="india"
print(senstive.format(name,place))

# enthusiastic="hey my name is {} and i am studing at {} college"
# name=input("enter your name:")
# college=input("enter your college name:")
# print(enthusiastic.format(name,college))

senstive="hey my name is {} and i am from {}"
name="nilesh"
place="india"
print(senstive.format(place,name))

senstive="hey my name is {0} and i am from {1}"   #mention index like address
name="\"nilesh\""
place="\"india\""
print(senstive.format(name,place))

juice="the price of apple juice only{price:.2f} and mango juice only{price1:.2f}"
print(juice.format(price=56.05776,price1=67.08877))


#use of f-string
senstive=f"my name is {name} and {place} is my country"
print(senstive)
senstive1=f"my name is {{name}} and {{place}} is my country"
print(senstive1)
apple="200"
mango="2000"
fruits=f'the prize of appple is {apple} and the prize of mango is {mango}'
print(f"i have {apple} apple and {mango} mango")
print(fruits)

banana=50.5467
papaya=40.5678
fruitjuice=f"the price of banana juice only {banana:.2f} and papaya juice only{papaya:.2f}"
print(fruitjuice)

print(type(f"{3*9}"))
# a=(input())
# b=(input())
# c=(f"{a+b}")
# print(c)
print(type(f"{3+9}"))
print((f"{3+9}"))

radhe radhe
hey my name is nilesh and i am from india
hey my name is india and i am from nilesh
hey my name is "nilesh" and i am from "india"
the price of apple juice only56.06 and mango juice only67.09
my name is "nilesh" and "india" is my country
my name is {name} and {place} is my country
i have 200 apple and 2000 mango
the prize of appple is 200 and the prize of mango is 2000
the price of banana juice only 50.55 and papaya juice only40.57
<class 'str'>
<class 'str'>
12

In [ ]:
print("radhe radhe")
#Docstring in python
# '''   '''  is a doc string not a comment it can changes the output but
#comment can not  (it just after function otherwise inter preter ignore it)

def square (n):
  '''Takes in number n and returns the square on n'''  #docstring
  print(n**2)
square(5)
square(10)
# we can print the doc string  like
print(square.__doc__)

#PEP 8 = python enhance ment propojal
#ester egg = import this ( write that on cmd and read the poem)
#The Zen of python

radhe radhe
25
100
Takes in number n and returns the square on n

In [ ]:
print("radhe radhe")
# Recurtion in python
def factorial(n):
  if (n==0 or n==1):
    return 1
  else:
    return n*factorial (n-1)
print(factorial(0))
print(factorial(1))
print(factorial(5))
print(factorial(10))
print(factorial(100))
print(factorial(9))
print(factorial(3))

def factorial(n):
  if(n==0):
    return 1
  elif (n==1):
    return 1
  else :
    return n*factorial(n-1)
print(factorial(6))

# recurence in femonaachi series
def febonacci(n):
  if(n==0):
    return 0
  elif(n==1):
    return 1
  else:
    return febonacci(n-1) + febonacci(n-2)
print(febonacci(1))
print(febonacci(6))
print(febonacci(0))
print(febonacci(10))
print(febonacci(15))
print(febonacci(20))
print(febonacci(25))

radhe radhe
1
1
120
3628800
93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000
362880
6
720
1
8
0
55
610
6765
75025

In [ ]:
from ast import Delete
print("radhe radhe")
#set data type  (it is unodered onwards python 3.7)
#sets do not contain duplicate item

a={5,5,4,5,3,5,6,8,7,8,10}
print(type(a),(a))  # set is unable to repeat the value

b={"seetaram",89,98.686,True,False,57856,28,28,28,"seetaram"}
print(b)

harry={}
print(type(harry),harry) #it give dictinary because both are same thats why
nilesh = set()
print(type(nilesh),nilesh)

#use for loop in set

silly={"om",876,867,986,958.595,True,876,False}
for value in silly:
  print(value)

#methods for manuputing the set data type

s1={1,2,3,}
s2={4,5,6,7,8}   # union() and update()
print(s1.union(s2))

raja={'op',"pp","pc"}
rani=("pp","oo","cc")
print(raja.union(rani))
print(s1,s2,raja,rani)

a1={6,7,9,8,10,11}
a2={1,2,3,4,7,8}
print(a1.union(a2))
print(a1,a2)
a1.update(a2)
print(a1)            # update is use to add a1 in a2 and a2 in a1
a2.update(a1)
print(a2)

#intersection() and update()
a1={6,7,9,8,10,11}
a2={1,2,3,4,7,8}
print(a1.intersection(a2))
print(a1,a2)
a1.intersection_update(a2)
print(a1)                  #common value show in a1
a2.intersection_update(a1)
print(a2)  #common value show in a2

cities1={'japan','bhootan','nepal','tokyo'}
cities2={'india','pak','america','nepal','china',"tokyo"}
cities3=cities1.intersection(cities2)
print(cities3)
cities1.intersection_update(cities2)
print(cities1)
cities2.intersection_update(cities1)
print(cities2)

#symmetric_difference()  use for find those value which are not common
cities1={'japan','bhootan','nepal','tokyo'}
cities2={'india','pak','america','nepal','china',"tokyo"}
cities3=cities1.symmetric_difference(cities2)
print(cities3)
a1={6,7,9,8,10,11}
a2={1,2,3,4,7,8}
print(a1.symmetric_difference(a2))
print(cities1,cities2)

#difference() and difference_update():
print(cities1.difference(cities2))
print(cities2.difference(cities1))

a1={6,7,9,8,10,11}
a2={1,2,3,4,7,8}
print(a1.difference(a2))
print(a1,a2)
print(a1.difference(a2))
print(a2.difference(a1))

#isdisjoint():  it use for joint the set (but both do not have any common value)
cities1={'japan','bhootan','nepal','tokyo'}
cities2={'india','pak','america','nepal','china',"tokyo"}
print(cities1.isdisjoint(cities2))      #give false because nepal and tokyo are common

cities3={'japan','bhootan','nepal@','tokyo@'}
cities4={'india','pak','america','nepal','china',"tokyo"}
print(cities3.isdisjoint(cities4))  # give true no common value


a1={6,7,9,8,10,11}
a2={1,2,3,4,7,8}
print(a1.isdisjoint(a2))

a3={6,7,9,8,10,11}
a4={1,2,3,4,71,81}
print(a3.isdisjoint(a4))

#issuperset():
cities1={'japan','bhootan','nepal','tokyo'}
cities2={'nepal',"tokyo"}
print(cities1.issuperset(cities2))  #if cities1 has all value of cities2 then citis1 called superset of cities2
print(cities2.issuperset(cities1))   # cities1 have all value of cities2 thats why output is true but cities2 does not have all value of citis1 thats why output is false

a3={6,7,9,8,10,11}
a4={1,2,3,4,7,8}
a5={7,8,10,11}
print(a3.issuperset(a4)) #a3 does not have all value of a4
print(a3.issuperset(a5)) #a3 have all value of a5

#issubset(): it is apposite of issuperset()
cities1={'japan','bhootan','nepal','tokyo'}
cities2={'nepal',"tokyo"}
print(cities2.issubset(cities1)) #cities2 called subset of citis1 if all value of citis2 belongs to the cities 1 (output give true otherwise false)
print(cities1.issubset(cities2))

a3={6,7,9,8,}
a4={1,2,3,4,9,6,7,8}
a5={7,8,10,11}
print(a3.issubset(a4))
print(a3.issubset(a5))

#.add() : use for add one item inside the set
cities1={'japan','bhootan','nepal','tokyo'}
cities1.add("india")
cities1.add("america")
print(cities1)

#.remove() and discard() : use for remove the item from set
cities1={'india',"japan","kanada","america","itli"}
cities1.remove("kanada")
print(cities1)
cities1.remove("japan")
print(cities1)
#cities1.remove("nepal") # it give error because nepal is not present in the set
#print(cities1)
cities1.discard("nepal")  # but it will not give error that we use discard sometime
print(cities1)
cities1.discard("itli")
print(cities1)

#pop(): it use for delete the any one random item fom set
cities1={'india',"japan","kanada","america","itli"}
cities1.pop()
print(cities1)
cities1.pop()     # nay item can be remove
print(cities1)

#del(): it is use for remove the entire set
cities={1,3,4,33,2.2,3.2,3.3,2.3}
del cities
#print(cities) it give erroe because cities set totaly Delete

#clear() : it is use for delete all item from set and make sure set is empty
cities={1,3,4,33,2.2,3.2,3.3,2.3}
cities.clear()
print(cities)
cities1={'india',"japan","kanada","america","itli"}
cities1.clear()
print(cities1)

# check if item exist

cities1={'india',"japan","kanada","america","itli","afgan"}
if "india" in cities1:
  print("good news india is present in the set")
else:
  print("bad news india is not present in the set")

radhe radhe
<class 'set'> {3, 4, 5, 6, 7, 8, 10}
{False, True, 98.686, 57856, 'seetaram', 89, 28}
<class 'dict'> {}
<class 'set'> set()
False
True
867
om
986
876
958.595
{1, 2, 3, 4, 5, 6, 7, 8}
{'cc', 'pp', 'op', 'oo', 'pc'}
{1, 2, 3} {4, 5, 6, 7, 8} {'pp', 'op', 'pc'} ('pp', 'oo', 'cc')
{1, 2, 3, 4, 6, 7, 8, 9, 10, 11}
{6, 7, 8, 9, 10, 11} {1, 2, 3, 4, 7, 8}
{1, 2, 3, 4, 6, 7, 8, 9, 10, 11}
{1, 2, 3, 4, 6, 7, 8, 9, 10, 11}
{8, 7}
{6, 7, 8, 9, 10, 11} {1, 2, 3, 4, 7, 8}
{8, 7}
{8, 7}
{'tokyo', 'nepal'}
{'tokyo', 'nepal'}
{'tokyo', 'nepal'}
{'pak', 'china', 'bhootan', 'america', 'india', 'japan'}
{1, 2, 3, 4, 6, 9, 10, 11}
{'tokyo', 'nepal', 'bhootan', 'japan'} {'tokyo', 'nepal', 'pak', 'china', 'america', 'india'}
{'bhootan', 'japan'}
{'china', 'pak', 'america', 'india'}
{9, 10, 11, 6}
{6, 7, 8, 9, 10, 11} {1, 2, 3, 4, 7, 8}
{9, 10, 11, 6}
{1, 2, 3, 4}
False
True
False
True
True
False
False
True
True
False
True
False
{'nepal', 'america', 'tokyo', 'bhootan', 'india', 'japan'}
{'itli', 'america', 'india', 'japan'}
{'itli', 'america', 'india'}
{'itli', 'america', 'india'}
{'america', 'india'}
{'itli', 'america', 'india', 'japan'}
{'america', 'india', 'japan'}
set()
set()
good news india is present in the set

In [ ]:
# print("radhe radhe")
# #dictionary in python    : it use for creating the mapping
# dic = {"nilesh": "human being" ,
#    "spoon" : "object" ,
#     231030 :  "nilesh gupta",
#     231012 :  "chnadni rangrej",
#     231025 :  "manoj singh patel",
#   #here 231025 ,231030 nilesh etc are kay and object, nilesh gupta etc are value
#  }

# print(dic["nilesh"])
# print(dic[231030])
# print(dic[231012])
# print(dic[231025])

# info={"name":"nilesh","age":18,"eligible":True}
# print(info)
# print(info["name"])
# print(info["age"])
# print(info["eligible"])
#                          # both are same but kay is wrong in .get it will give none
# print(info.get("name"))
# print(info.get('age'))
#                        # if key is not exist in the dictionary
# # print(info ["name2"])  # it will give error
# print(info.get("name2")) # it will give none and execute the code

# #access all key
# print(info.keys())
# print(dic.keys())

# # access all value
# print(info.values())    #give all in odered way
# print(dic.values())


# # accessall value
# for key in info.keys():   # give all in odered way
#   print(info[key])
# for key in dic.keys():
#   print(dic[key])

# #access all keys along with the values
# for key in info.keys():
#   print(f"the value corresponding to the {key} is {info[key]}")
# for key in dic.keys():
#   print(f"the value corresponding to the {key} is {dic[key]}")

# print(dic.items())    # it will give key value pairs
# print(info.items())

# for key,value in info.items():
#   print(f"the value corresponding to the key {key} is {value}")

# for key,value in dic.items():
#   print(f"the value corresponding to the key {key} is {value}")



#methods use in dictionary   (it is odered onwards python 3.7 )
#update : use for add one dictionary keys and value from another dictionary
ep1={122:45,133:50,144:60,155:70,166:90}
ep2={211:78,233:87}    #ep1 add keys and value from ep2 keys and value
print(ep1,ep2)
ep1.update(ep2)
print(ep1)
ep2.update(ep1)
print(ep2)

hiteshsir={"manoj":96,"shrishti":95,"yash":94,"ishan":93}
varshmam={"imran":94,"nilesh":96}
print(hiteshsir,varshmam)
hiteshsir.update(varshmam)
print(hiteshsir)
varshmam.update(hiteshsir)
print(varshmam)

#clear method : use for remove all keys and value from dictionary
humble={"Nilesh gupta":1,"bikash gupta":2,"swati gupta":3,"ritesh gupta":4,"jyoti gupta":5}
print(humble)
humble.clear()
print(humble)

empt={} #it is use for create a empty dictionary
print(empt)

#pop method : use for remove the keys value pair

ep1={122:45,133:50,144:60,155:70,166:90}
ep2={211:78,233:87}
print(ep1,ep2)
ep1.pop(122,133)       # remove keys and value both along with
print(ep1)
ep2.pop(211)
print(ep2)

#popitem :ot use for remove the last keys value pair

ep1={122:45,133:50,144:60,155:70,166:90}
ep2={211:78,233:87}    #ep1 add keys and value from ep2 keys and value
print(ep1,ep2)
ep1.popitem()
print(ep1)
ep2.popitem()
print(ep2)

#del :use for delete the complete dictionary
ep1={122:45,133:50,144:60,155:70,166:90}
ep2={211:78,233:87}
print(ep1,ep2)
del ep1,ep2         # delete both dictionary ep1 and ep2
# print(ep1,ep2)
# del ep1
# print(ep1)
# del ep2
# print(ep2)

ep1={122:45,133:50,144:60,155:70,166:90}
ep2={211:78,233:87}
del ep1[122]  # it delete only given kays and there value
print(ep1)
del ep2[211]
print(ep2)

#go google and search python dictionary documentation

{122: 45, 133: 50, 144: 60, 155: 70, 166: 90} {211: 78, 233: 87}
{122: 45, 133: 50, 144: 60, 155: 70, 166: 90, 211: 78, 233: 87}
{211: 78, 233: 87, 122: 45, 133: 50, 144: 60, 155: 70, 166: 90}
{'manoj': 96, 'shrishti': 95, 'yash': 94, 'ishan': 93} {'imran': 94, 'nilesh': 96}
{'manoj': 96, 'shrishti': 95, 'yash': 94, 'ishan': 93, 'imran': 94, 'nilesh': 96}
{'imran': 94, 'nilesh': 96, 'manoj': 96, 'shrishti': 95, 'yash': 94, 'ishan': 93}
{'Nilesh gupta': 1, 'bikash gupta': 2, 'swati gupta': 3, 'ritesh gupta': 4, 'jyoti gupta': 5}
{}
{}
{122: 45, 133: 50, 144: 60, 155: 70, 166: 90} {211: 78, 233: 87}
{133: 50, 144: 60, 155: 70, 166: 90}
{233: 87}
{122: 45, 133: 50, 144: 60, 155: 70, 166: 90} {211: 78, 233: 87}
{122: 45, 133: 50, 144: 60, 155: 70}
{211: 78}
{122: 45, 133: 50, 144: 60, 155: 70, 166: 90} {211: 78, 233: 87}
{133: 50, 144: 60, 155: 70, 166: 90}
{233: 87}

In [ ]:
print("radhe radhe")
# for loop with else in python
# note range works only from 0 to n-1

for i in range(5):
  print(i)
else:
  print("sorry no i")


for i in []:
  print(i)
else:
  print("sorry no i")

for i in range(6):
  print(i)
  if i==4:
    break            #her loop in break afte i=4
else:
  print("sorry no i")

i=0
while i<7:
  print(i)
  i=i+1
  if i==4 :       # break statement stop the loop after satisfying the condition
    break
else:
  print("sorry no i")


i=0
while i<7:
  print(i)
  i=i+1
  # if i==4 :
  #   break
else:
  print("sorry no i")

for x in range(5):
  print("iteration no {} in for loop".format(x+1))
else:
  print("else block in loop")
print("out of loop")

radhe radhe
0
1
2
3
4
sorry no i
sorry no i
0
1
2
3
4
0
1
2
3
0
1
2
3
4
5
6
sorry no i
iteration no 1 in for loop
iteration no 2 in for loop
iteration no 3 in for loop
iteration no 4 in for loop
iteration no 5 in for loop
else block in loop
out of loop

In [ ]:
print("radhe radhe")
# #Exception hndling
#try except in python


# a= input("enter the number:")
# print(f"multiplication table of {a} is:")
# try:
#   for i in range(1,11):
#     print(f"{int(a)}x{i} = {int(a)*i}")
# except:
#   print("invalid input")

# print("some important line of code")
# print("end of program")

# a= input("enter the number:")
# print(f"multiplication table of {a} is:")

# try:
#   for i in range(1,11):
#     print(f"{int(a)}x{i} = {int(a)*i}")
# except:
#   print("sorry invalid input")

# print("some important line of code")
# print("end of program")

# try:
#   num = int(input("enter an integer:"))
# except ValueError:
#     print("number entered is not an integer")




# try:
#   num = int(input("enter an integer:"))
#   a=[6,3]
#   print(a[num])
# except ValueError:
#     print("number entered is not an integer")
# except IndexError:
#   print("Index rror")


# try:
#   num = int(input("enter an integer:"))
#   a=[6,3]
#   print(a[num])
# except ValueError:
#     print("number entered is not an integer")
# except IndexError:
#   print("Index Error")


#finally in python : it is very use full when we work with function on python

# def fucn1():
#   try:
#     l=[1,2,4,3]
#     i=int(input("enter the index:"))
#     print(l[i])
#     return 1
#   except:
#     print("some error occured")
#     return 0

#   print("i am aiways executed")

# x=fucn1()
# print(x)


# now we use finally

# def fucn1():

#   try:
#     l=[1,2,4,3]
#     i=int(input("enter the index:"))
#     print(l[i])
#     return 1
#   except:
#     print("some error occured")
#     return 0

#   finally:
#    print("i am aiways executed")

# x=fucn1()
# print(x)



# def fucn1():

#   try:
#     l=[1,2,4,3]
#     i=int(input("enter the index:"))
#     print(l[i])
#     return 1
#   except:
#     print("some error occured")
#     return 0

#   finally:
#     print("i am aiways executed")

# x=fucn1()
# print(x)


# def fucn1():

#   try:
#     l=[1,2,4,3]
#     i=int(input("enter the index:"))
#     print(l[i])
#     return 1
#   except:
#     print("some error occured")
#     return 0

#   # finally:
# print("i am aiways executed")

# x=fucn1()
# print(x)


numbers = [10, 20, 30, 40]

try:
    index = int(input("Enter an index (0-3): "))
    print("Value:", numbers[index])

except IndexError:
    print("Error: Index is out of range.")

radhe radhe
Enter an index (0-3): 4
Error: Index is out of range.

In [ ]:
print("radhe radhe")
# raising custom errors
# a=int(input("enter any value between 5 and 9:"))
# if(a<5 or a>9):
#   raise ValueError("value should be between 5 and 9")

name = input("enter your name (at least 3 characters):")
if len(name) < 3 :
  raise valueerror

radhe radhe

MyError: something went wrong

In [ ]:
#project kaun bnega krorepti
questions = [["which language was used to create facebook?","pyhton","java","javascript","php","none",4],
["which language was used to create facebook?","pyhton","java","javascript","c++","none",4],
["which language was used to create facebook?","pyhton","java","javascript","c++","none",4],
["which language was used to create facebook?","pyhton","java","javascript","c++","none",4],
["which language was used to create facebook?","pyhton","java","javascript","c++","none",4],
["which language was used to create facebook?","pyhton","java","javascript","c++","none",4],
["which language was used to create facebook?","pyhton","java","javascript","c++","none",4]]
levels=[1000,2000,3000,5000,10000,20000,40000,80000,160000,320000]
money = 0
for i in range(0, len(questions)):
  question = questions[i]
  print(f"question for rs. {levels[i]}")
  print(f"a.{question[1]}    b.{question[2]}")
  print(f"c.{question[3]}    d.{question[4]}")
  reply = int(input("enter your answer (1-4):"))
  if (reply==question[-1]):
    print(f"correct answer , you have won rs. {levels [i]}")
    if(i==4):
      money = 10000
    elif(1==9):
       money = 3200000

    elif(i==14):
       money = 10000000

  else:
    print("wrong answer")
    break
print(f"your take home money is {money}")

question for rs. 1000
a.pyhton    b.java
c.javascript    d.php
enter your answer (1-4):4
correct answer , you have won rs. 1000
question for rs. 2000
a.pyhton    b.java
c.javascript    d.c++
enter your answer (1-4):4
correct answer , you have won rs. 2000
question for rs. 3000
a.pyhton    b.java
c.javascript    d.c++
enter your answer (1-4):4
correct answer , you have won rs. 3000
question for rs. 5000
a.pyhton    b.java
c.javascript    d.c++
enter your answer (1-4):4
correct answer , you have won rs. 5000
question for rs. 10000
a.pyhton    b.java
c.javascript    d.c++
enter your answer (1-4):4
correct answer , you have won rs. 10000
question for rs. 20000
a.pyhton    b.java
c.javascript    d.c++
enter your answer (1-4):5
wrong answer
your take home money is 10000

In [ ]:
print("radhe radhe")
#excercise

'''write a python program to translate a messege into secret code language
by using thes rules.

coding:
1.if the word contain atleast three characters ,remove the first letter and append it at the end.
2.now append three random character at the starting and at the end
else:
  simply revese the string
decoding :
1. if the word contain less than three characters , revese it
else:
  1.remove three random character from start and end
  2. remove the last latter and append it to the start'''
  #your program should ask whether you want to decode or code


import random
import string

# Random 3 अक्षर बनाने के लिए
def generate_random_chars(length=3):
    return ''.join(random.choices(string.ascii_letters, k=length))

# एक शब्द को Encode करना
def encode_word(word):
    if len(word) >= 3:
        # पहला अक्षर हटाओ और आख़िर में जोड़ो
        transformed = word[1:] + word[0]
        # 3 random अक्षर आगे और पीछे जोड़ो
        prefix = generate_random_chars()
        suffix = generate_random_chars()
        return prefix + transformed + suffix
    else:
        # अगर शब्द 3 से छोटा है तो उसे उल्टा कर दो
        return word[::-1]

# एक शब्द को Decode करना
def decode_word(word):
    if len(word) < 3:
        return word[::-1]
    else:
        # शुरू और अंत के 3–3 random अक्षर हटाओ
        core = word[3:-3]
        # आख़िरी अक्षर को शुरू में लाओ
        return core[-1] + core[:-1]

# पूरा मैसेज Encode करना
def encode_message(message):
    words = message.split()
    return ' '.join(encode_word(word) for word in words)

# पूरा मैसेज Decode करना
def decode_message(message):
    words = message.split()
    return ' '.join(decode_word(word) for word in words)

# चलाने वाला भाग
if __name__ == "__main__":
    original = input("🔤 Encode करने के लिए कोई मैसेज डालिए: ")

    encoded = encode_message(original)
    print(f"\n🟢 Encoded Message: {encoded}")

    decoded = decode_message(encoded)
    print(f"🔁 Decoded Message: {decoded}")

radhe radhe
🔤 Encode करने के लिए कोई मैसेज डालिए: i love you

🟢 Encoded Message: i nuWovelLQo MoMouycQz
🔁 Decoded Message: i love you

In [ ]:
# short hand if else : use for time saving

a= 200
b=300
print("a") if(a<b) else print("=")
a= 200
b=300
print("a") if(a>b) else print("=") if(a==b) else print("b")

num = -5
result = 'positive' if num >=0 else "negtive"
print(result)

n=10
print("even" if (n==5*2) else "odd")
age=17
lively="adult" if age>=18 else "minor"
print(lively)
a=100
b=200
max_value = a if a>b else b
print("max:" ,max_value)
marks=95
print("pass" if(marks>90) else "fail")

a
b
negtive
even
minor
max: 200
pass

In [ ]:
# Enumerate() function
marks=[90,89,88,97,98,95]
# index = 0
# for mark in marks :
#   print(mark)
#   if (index==4):
#     print("radhe radhe")
#   index += 1

for index,mark in enumerate(marks):
  print( index, mark)
  if (index==4):
    print("kya baat hai")

fruits=["mango","orange","banana","papaya"]
for index,fruit in enumerate(fruits):
  print(fruit)

fruits=["mango","orange","banana","papaya"]
for index,fruit in enumerate(fruits):
  print(index,fruit)


fruits = ["apple", "banana", "cherry"]

for index, fruit in enumerate(fruits, start=1):
    print(f"{index}. {fruit}")

for index, char in enumerate("hello"):
    print(index, char)


for index,mark in enumerate(marks,start=1):
  print(index,mark)
  if (index==4):
    print("kya baat hai")

0 90
1 89
2 88
3 97
4 98
kya baat hai
5 95
mango
orange
banana
papaya
0 mango
1 orange
2 banana
3 papaya
1. apple
2. banana
3. cherry
0 h
1 e
2 l
3 l
4 o
1 90
2 89
3 88
4 97
kya baat hai
5 98
6 95

In [ ]:
print("radhe radhe")
import pandas as pd
print(pd.__version__)

radhe radhe
2.2.2

In [ ]:
print("radhe radhe")
#import in python
import math
print(math.floor(4.23445))
print(int(math.sqrt(9)))

from math import sqrt,pi
a=sqrt(9)
b=pi
print(f"sqrt of 9 is {a} and pi is {b}")
result=a*b
print(result)

# import math
print(dir(math))
print(math.nan , type(math.nan))

from math import pi,sqrt as s
print(s(25))
a=math.sqrt(16) * math.pi
print(a)
# from math import pi,sqrt as s
import math as m
print(s(25))
a=m.sqrt(16) * m.pi
print(a)

radhe radhe
4
3
sqrt of 9 is 3.0 and pi is 3.141592653589793
9.42477796076938
['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']
nan <class 'float'>
5.0
12.566370614359172
5.0
12.566370614359172

In [ ]:
print("radhe radhe")
print(s(100))

radhe radhe
10.0

In [1]:
print("radhe radhe")

radhe radhe